### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by easyiit** [GoAdminGroup/go-admin#261] opened 2020-06-01 03:34 UTC
### Description [describe your questions]

```
../github.com/GoAdminGroup/go-admin/adapter/beego/beego.go:52:76: undefined: admin.AddOperationFn
../github.com/GoAdminGroup/go-admin/adapter/beego/beego.go:53:16: too many arguments in call to bee.BaseAdapter.GetContent

GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/niujinhui/Library/Caches/go-build"
GOENV="/Users/niujinhui/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Volumes/golang"
GOPRIVATE=""
GOPROXY="https://mirrors.aliyun.com/goproxy/,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5w/byfcc3ps54gb2xn2bh5b9sgw0000gn/T/go-build894996704=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by chenhg5** [comment] 2020-06-05 06:15
Duplicate of #248

**Comment by chenhg5** [comment] 2020-06-05 06:16
Duplicate of #248

**Closed by chenhg5** 2020-06-05 06:16 UTC
