### ISSUE TITLE
[Question]multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by cui3093** [GoAdminGroup/go-admin#114] opened 2019-12-13 06:48 UTC
### Description [describe your questions]

[root@localhost go-admin]# go get github.com/GoAdminGroup/themes/adminlte
github.com/GoAdminGroup/go-admin/plugins/admin/modules
/opt/Golang/goadmin/src/github.com/GoAdminGroup/go-admin/plugins/admin/modules/helper.go:60:19: multiple-value uuid.NewV4() in single-value context

**Comment by chenhg5** [comment] 2019-12-13 07:18
#93

**Comment by chenhg5** [comment] 2019-12-13 07:19
Duplicate of #93

**Comment by godcong** [comment] 2019-12-20 09:21
github.com/satori/go.uuid v1.2.0  only one value return
github.com/satori/go.uuid@master has two value return
check your go.uuid version ,which you used.

**Closed** 2020-02-20 06:05 UTC
